#!/bin/bash
# Version v0.0.1
# Author: Hugo ChunHo Lin
# GitHub: github.com/1chooo
# Copyright (C) 2023 Hugo ChunHo Lin All rights reserved.

# Delete the local branch 'ho-dev'
git branch -d ho-dev

# Create a new local branch 'ho-dev' and switch to it
git checkout -b ho-dev

# Push the 'ho-dev' branch to the remote 'origin'
git push origin ho-dev

# Switch back to the 'main' branch
git checkout main

# open the origin branch github page
local remote_url=$(git config --get remote.origin.url)

if [[ $remote_url == *"github.com"* ]]; then
# Convert SSH URL to HTTPS URL
remote_url=${remote_url/git@github.com:/https:\/\/github.com\/}
remote_url=${remote_url/\.git/}/compare/main...ho-dev

# Open the URL in the default browser
open "$remote_url"
else
echo "Remote origin is not a GitHub repository."

fi 

# Sleep for 2 minutes (120 seconds)
sleep 120

# Fetch changes from the upstream repository
git fetch upstream

# Merge changes from 'upstream/main' into the current branch
git merge upstream/main