#!/bin/zsh
# Version v0.0.1
# Author: Hugo ChunHo Lin
# GitHub: github.com/1chooo
# Copyright (C) 2023 Hugo ChunHo Lin All rights reserved.

if [[ "$1" == *.cpp ]]; then
  output="${1%.cpp}"
elif [[ "$1" == *.c ]]; then
	output="${1%.c}"
else
  output="$1"
fi


gcc "$output".c -o "$output".out 2> /dev/null || clang++ -std=c++17 -stdlib=libc++ "$output".cpp -o "$output".out 2> /dev/null

"$PWD/$output".out

#if [[ "$?" == 1 ]]; then
#	clang++ -std=c++17 -stdlib=libc++ "$output".cpp -o "$output".out && "$PWD/$output".out
#fi

exit 0
